arshad-terrform
AtiwadkarAjinkya/DevOps-Practice_repo pull request #5
Opened 2021-09-30 07:49 UTC by sulaim09

terraform command

2021-09-30 07:50 UTC, sulaim09 commented
sir  plz check

2021-09-30 08:01 UTC, AtiwadkarAjinkya requested changes
Change the File format to .tf

2021-10-05 03:48 UTC, AtiwadkarAjinkya requested changes

2021-10-05 03:48 UTC, AtiwadkarAjinkya commented on arshad-Terrform.txt.txt
> +  instance_type = "t3.micro"
Make it to t2.micro

2021-10-05 14:38 UTC, sulaim09 reviewed
changes file extension

2021-10-05 14:38 UTC, merged